config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'sandboxes/show'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: %i[create destroy]

  resource :home, only: [:show]
  resource :style_guide, only: [:show]
  resource :about, only: [:show]
  resource :sandbox, only: [:show]
  resource :composition, only: [:update]

  resources :notes, only: %i[create destroy]

  root to: 'homes#show'
end

app/views/partials/_annotations.haml
.sandbox__annotations
  %h4.sandbox__annotations-header
    = header
  - if annotations.empty?
    .sandbox__annotation
      = t('.perfect_score')
  - annotations.each do |annotation|
    .sandbox__annotation{ class: "sandbox__annotation--#{annotation.start_position.to_s.to_i}" }
      .sandbox__annotation-marks
        - [annotation.marks].flatten.each do |mark|
          .sandbox__annotation-mark
            = "#{mark.start_position.bar_number}:#{mark.start_position.count}"
      .sandbox__annotation-fitness= annotation.fitness.round(3)
      .sandbox__annotation-message= annotation.message

app/views/partials/_composition.haml
%h2.sandbox__title= composition.name
= form_for(composition, url: {controller: 'compositions', action: 'update', id: composition.id}, html: {class: 'sandbox__form'}) do |f|
  .sandbox__key-signature
    = f.select(:key_signature, ["C major", "D dorian", "E phrygian", "F lydian", "G mixolydian", "A aeolian"], {}, { onchange: "this.form.submit();" })
  .sandbox__voice
    - if @sandbox.voice_cantus_firmus?
      = t('.entering_cantus_firmus')
      = link_to t('.enter_counterpoint'), sandbox_path, class: 'button form-widget'
    - else
      = t('.entering_counterpoint')
      = link_to t('.enter_cantus_firmus'), sandbox_path(voice: 'cantus_firmus'), class: 'button form-widget'

app/views/partials/_score.haml
%table.sandbox__score{ class: "sandbox__score--#{sandbox.voice_role_modifier}" }
  %thead
    %tr
      - (0..[sandbox.highest_bar+1, 8].max).each do |bar|
        %th
          = bar if bar > 0
  %tbody
    - sandbox.pitches.reverse.each do |pitch|
      - accidental = pitch.sign.present?
      - no_flat = pitch.letter_name.name.in?(%w[C F])
      - no_sharp = pitch.letter_name.name.in?(%w[B E])
      - white_type = no_flat ? 'no-flat' : (no_sharp ? 'no-sharp' : 'flat-and-sharp')
      %tr.sandbox__pitch{class: "sandbox__pitch--#{accidental ? 'black' : 'white'}"}
        %th.sandbox__pitch-piano-key
          - if accidental.present?
            .sandbox__piano-key.sandbox__piano-key--black
              .sandbox__piano-key-half
                .sandbox__piano-key-back.sandbox__piano-key-back--upper-half
                .sandbox__piano-key-front.sandbox__piano-key-front--upper-half
              .sandbox__piano-key-half
                .sandbox__piano-key-back.sandbox__piano-key-back--lower-half
                .sandbox__piano-key-front.sandbox__piano-key-front--lower-half
          - else
            .sandbox__piano-key.sandbox__piano-key--white{class: "sandbox__piano-key--#{white_type}"}
        - (1..[sandbox.highest_bar+1, 8].max).each do |bar|
          - note = sandbox.voices.map(&:notes).flatten.detect { |note| note.bar == bar && note.pitch == pitch.name }
          %td.sandbox__pitch-bar{class: "sandbox__pitch-bar--#{cycle('odd', 'even')}", data: {bar: bar, pitch: pitch.name, voice: note&.voice}}
            - if note.nil?
              = link_to('', notes_url(note: {bar: bar, pitch: pitch, voice_id: sandbox.voice_id}), method: :post, class: "sandbox__note-link sandbox__note-link--create")
            - else
              = link_to('', note_url(note), method: :delete, class: "sandbox__note-link sandbox__note-link--delete sandbox__note-link--#{note.voice.role.dasherize}")

app/views/partials/_voice.haml
.voice
  .voice-label
    = voice.label