config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'sandboxes/show'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: %i[create destroy]

  resource :home, only: [:show]
  resource :style_guide, only: [:show]
  resource :about, only: [:show]
  resource :sandbox, only: [:show]
  resource :composition, only: [:update]

  resources :notes, only: %i[create destroy]

  root to: 'homes#show'
end

app/views/layouts/_messages.haml
- [:success, :info, :alert, :danger].each do |level|
  - if messages[level].present?
    .messages__section{class: "messages__section--#{level}", id: "messages__section--#{level}"}
      - [messages[level]].flatten.each do |message|
        .message
          = message

app/views/layouts/_top_nav.haml
%nav.top-nav
  .top-nav__spread
    .top-nav__container.page__container
      .top-nav__content.top-nav__content--brand
        = link_to(home_path, class: "top-nav__brand-link") do
          = t(:name, scope: [:site])
      .top-nav__content.top-nav__content--menu
        %ul.top-nav__menu-list
          %li.top-nav__menu-list-item
            = link_to_unless_current(t('.home'), home_path, class: 'top-nav__menu-link')
          %li.top-nav__menu-list-item
            = link_to_unless_current(t('.compositions'), sandbox_path, class: 'top-nav__menu-link')
          - if false
            %li.top-nav__menu-list-item
              = link_to_unless_current(t('.about'), about_path, class: 'top-nav__menu-link')
          %li.top-nav__menu-list-item
            - if current_identity
              = link_to t('.sign_out'), signout_path, id: "sign_out", class: 'top-nav__menu-link'
            - else
              = link_to t('.sign_in'), "/auth/google_oauth2", id: "sign_in", class: 'top-nav__menu-link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
      = t(:name, scope: [:site])
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    :css
      @import url('https://fonts.googleapis.com/css?family=Cormorant+Garamond');
  %body#juxtacompose
    .page__spread
      = render partial: 'layouts/top_nav'
      = render partial: 'layouts/messages', locals: {messages: flash}
      %main.page__container.page__container--main
        = yield

app/views/layouts/sandbox.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
      = t(:name, scope: [:site])
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{src: 'https://tonejs.github.io/build/Tone.js'}
    :css
      @import url('https://fonts.googleapis.com/css?family=Cormorant+Garamond');
  %body#juxtacompose
    .page__spread
      = render partial: 'layouts/top_nav'
      = render partial: 'layouts/messages', locals: {messages: flash}
      %main.page__container.page__container--sandbox
        = yield